const suggestions = [
    "Graphic Design",
    "Web Design",
    "Illustration",
    "Photography",
    "Digital Art",
    "UI/UX",
    "Branding",
    "Typography",
    "Motion Graphics",
    "Animation",
    "Product Design",
    "Architecture",
    "Fashion",
    "Game Design",
    "Art Direction",
    "Print Design",
    "Packaging",
    "Advertising",
    "Logo Design",
    "Interactive Design",
    "Street Photography",
    "Fine Arts",
    "Experimental",
    "Mobile App Design",
    "Vector Art",
    "3D Modeling",
    "Video Editing",
    "Cinematography",
    "Virtual Reality",
    "Augmented Reality",
    "Social Media",
    "Event Design",
    "Icon Design",
    "Infographics",
    "Book Design",
    "Magazine Design",
    "Poster Design",
    "Comic Art",
    "Pattern Design",
    "T-shirt Design",
    "Character Design",
    "Caricature",
    "Sculpture",
    "Crafts",
    "Digital Painting",
    "Game Development",
    "Sound Design",
    "UI/UX Prototyping",
    "Wireframing",
    "User Research",
    "User Testing",
    "Design Thinking",
    "Color Theory",
    "Photomanipulation",
    "Street Art",
    "Landscape Photography",
    "Nature Photography",
    "Portrait Photography",
    "Abstract Art",
    "Minimalism",
    "Surrealism",
    "Realism",
    "Pop Art",
    "Impressionism",
    "Expressionism",
    "Modern Art",
    "Contemporary Art"
];

// Use this 'suggestions' array in your existing code for autocomplete.
